#!/bin/sh
arg="$1"

if [ $arg != "-h" ]; then
        echo "Run rvx -h for help"
fi

if [ $arg = "-d" ]; then
        killall vxwm 2>/dev/null
        dbus-run-session vxwm -ignoreautostart
elif [ $arg = "-h" ]; then
        echo "rvx:                A tool designed for quickly restarting vxwm"
        echo "rvx -d:             Restarts vxwm with dbus-run-session"
        echo "rvx -h:             Show this message"
else
        killall vxwm 2>/dev/null
        vxwm -ignoreautostart
fi
