/* AUTO GENERATED BY MATUGEN */
static const char matugen_bg[]      = "{{colors.background.default.hex}}";
static const char matugen_fg[]      = "{{colors.on_background.default.hex}}";
static const char matugen_border[]  = "{{colors.primary.default.hex}}";
static const char matugen_sel_bg[]  = "{{colors.primary_container.default.hex}}";
