/* AUTOGENERATED BY MATUGEN */ 

#ifndef VXWM_MATUGEN_COLORS_H
#define VXWM_MATUGEN_COLORS_H 

#define MATUGEN_BG      "{{colors.background.default.hex}}"
#define MATUGEN_FG      "{{colors.on_background.default.hex}}"
#define MATUGEN_BORDER  "{{colors.primary.default.hex}}"
#define MATUGEN_SEL_BG  "{{colors.primary_container.default.hex}}" 

#endif // VXWM_MATUGEN_COLORS_H
